### ISSUE TITLE
DEGA paradrop seemed to not work from C47

### ISSUE THREAD

**Issue by bsoWalker** [Beowulf-Arms/BeowulfArms-Mods#26]

**Comment by bsoWalker** [comment]
@Keithenneu implemented a temp fix for now to apply to all vechs.

`dega_static_line_disabled` variable does exist. SO could be used for missionmakers to disable if they really want to.

**Comment by Keithenneu** [comment]
C-47 proved to be un-cooperative, so this is now the permanent fix.

(tl;dr: no doors, nor para memory point that I could find -> handled as any other aircraft)
