### ISSUE TITLE
Issue with convoy module

### ISSUE THREAD

**Issue by Trenchf00tt** [Beowulf-Arms/BeowulfArms-Mods#37]
Place down module, sync each vehicle in order of march. Launch game.
Error appears as in screenshot.
Convoy still works as intended.

![20230202170418_1](https://user-images.githubusercontent.com/98166712/216399004-6532a4b6-d4e6-4ef6-b235-30ff635397f1.jpg)
![20230202172324_1](https://user-images.githubusercontent.com/98166712/216399041-710e5b0a-ddfa-4964-a0af-c3a375c74e24.jpg)

**Comment by bsoWalker** [comment]
Something to report to the mod maker
